### ISSUE TITLE
Parameter -Registry does not work

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/New-Tattoo#1]
According to comments from blog:

> That was the thing. I didn’t see an error but it didn’t work as expected. I simply changed the Parameters within the task to -All instead of -Registry (with no other modifications) and it worked. I didn’t know exactly what to edit (if I needed to) based on one of the previous comments since there were a lot of values and properties between lines 936-956 as mentioned by Kyle on 10/13/2017. Not sure if it’s some sort of bug or there needs to be a “1.4.4” version with the fixes.

and

>I downloaded v1.4.3 and only the “All” switch would work. I was trying to run the “Registry” switch only but kept getting an error about a bad parameter called “name”. Comparing the parameters on line 936 to lines 941, 946, 951, and 956 there is a mismatch between the parameters. “Name” should be **“PropertyName” and “Value” should be “PropertyValue”**. Once I made the change the registry switch worked fine.

**Comment by chroswalt** [comment]
I added a fork and pull request to fix this issue.

**Comment by Stephanevg** [comment]
Thanks for the PR @chroswalt !! 
I just merged it a few seconds ago
Fix https://github.com/Stephanevg/New-Tattoo/pull/2

**Comment by Stephanevg** [comment]
Fix #2
